<?php
declare(strict_types=1);

$classMap = [
	'Psr\\Container\\ContainerExceptionInterface'                          => __DIR__ . '/../../psr/container/src/ContainerExceptionInterface.php',
	'Psr\\Container\\ContainerInterface'                                   => __DIR__ . '/../../psr/container/src/ContainerInterface.php',
	'Psr\\Container\\NotFoundExceptionInterface'                           => __DIR__ . '/../../psr/container/src/NotFoundExceptionInterface.php',
	'SuperKernel\\Annotator\\Annotation'                                   => __DIR__ . '/../annotator/src/Annotation.php',
	'SuperKernel\\Annotator\\AnnotationCacheCollector'                     => __DIR__ . '/../annotator/src/AnnotationCacheCollector.php',
	'SuperKernel\\Annotator\\AnnotationCollector'                          => __DIR__ . '/../annotator/src/AnnotationCollector.php',
	'SuperKernel\\Annotator\\Factory\\AnnotationCollectorFactory'          => __DIR__ . '/../annotator/src/Factory/AnnotationCollectorFactory.php',
	'SuperKernel\\Annotator\\Provider\\AnnotationCollectorProvider'        => __DIR__ . '/../annotator/src/Provider/AnnotationCollectorProvider.php',
	'SuperKernel\\Attribute\\Autowired'                                    => __DIR__ . '/../attribute/src/Autowired.php',
	'SuperKernel\\Attribute\\Factory'                                      => __DIR__ . '/../attribute/src/Factory.php',
	'SuperKernel\\Attribute\\Listener'                                     => __DIR__ . '/../attribute/src/Listener.php',
	'SuperKernel\\Attribute\\Provider'                                     => __DIR__ . '/../attribute/src/Provider.php',
	'SuperKernel\\Bootstrap\\Bootstrap'                                    => __DIR__ . '/src/Bootstrap.php',
	'SuperKernel\\Bootstrap\\Provider\\ClassLoaderProvider'                => __DIR__ . '/src/Provider/ClassLoaderProvider.php',
	'SuperKernel\\Bootstrap\\Provider\\ContainerProvider'                  => __DIR__ . '/src/Provider/ContainerProvider.php',
	'SuperKernel\\ClassLoader\\ClassLoader'                                => __DIR__ . '/../class-loader/src/ClassLoader.php',
	'SuperKernel\\ClassLoader\\Provider\\ClassLoaderProvider'              => __DIR__ . '/../class-loader/src/Provider/ClassLoaderProvider.php',
	'SuperKernel\\ComposerResolver\\ComposerJsonReader'                    => __DIR__ . '/../composer-resolver/src/ComposerJsonReader.php',
	'SuperKernel\\ComposerResolver\\ComposerLockReader'                    => __DIR__ . '/../composer-resolver/src/ComposerLockReader.php',
	'SuperKernel\\ComposerResolver\\Concerns\\JsonReaderTrait'             => __DIR__ . '/../composer-resolver/src/Concerns/JsonReaderTrait.php',
	'SuperKernel\\ComposerResolver\\Contract\\ComposerJsonReaderInterface' => __DIR__ . '/../composer-resolver/src/Contract/ComposerJsonReaderInterface.php',
	'SuperKernel\\ComposerResolver\\Contract\\ComposerLockReaderInterface' => __DIR__ . '/../composer-resolver/src/Contract/ComposerLockReaderInterface.php',
	'SuperKernel\\ComposerResolver\\Factory\\PackageCollectorFactory'      => __DIR__ . '/../composer-resolver/src/Factory/PackageCollectorFactory.php',
	'SuperKernel\\ComposerResolver\\Factory\\PackageFactory'               => __DIR__ . '/../composer-resolver/src/Factory/PackageFactory.php',
	'SuperKernel\\ComposerResolver\\Package'                               => __DIR__ . '/../composer-resolver/src/Package.php',
	'SuperKernel\\ComposerResolver\\PackageCollector'                      => __DIR__ . '/../composer-resolver/src/PackageCollector.php',
	'SuperKernel\\ComposerResolver\\Provider\\ComposerJsonReaderProvider'  => __DIR__ . '/../composer-resolver/src/Provider/ComposerJsonReaderProvider.php',
	'SuperKernel\\ComposerResolver\\Provider\\ComposerLockReaderProvider'  => __DIR__ . '/../composer-resolver/src/Provider/ComposerLockReaderProvider.php',
	'SuperKernel\\ComposerResolver\\Provider\\PackageCollectorProvider'    => __DIR__ . '/../composer-resolver/src/Provider/PackageCollectorProvider.php',
	'SuperKernel\\Context\\ApplicationContext'                             => __DIR__ . '/../context/src/ApplicationContext.php',
	'SuperKernel\\Context\\Context'                                        => __DIR__ . '/../context/src/Context.php',
	'SuperKernel\\Contract\\AnnotationCollectorInterface'                  => __DIR__ . '/../contract/src/AnnotationCollectorInterface.php',
	'SuperKernel\\Contract\\AnnotationInterface'                           => __DIR__ . '/../contract/src/AnnotationInterface.php',
	'SuperKernel\\Contract\\ClassAutoloaderInterface'                      => __DIR__ . '/../contract/src/ClassAutoloaderInterface.php',
	'SuperKernel\\Contract\\ContainerInterface'                            => __DIR__ . '/../contract/src/ContainerInterface.php',
	'SuperKernel\\Contract\\PackageCollectorInterface'                     => __DIR__ . '/../contract/src/PackageCollectorInterface.php',
	'SuperKernel\\Contract\\PackageInterface'                              => __DIR__ . '/../contract/src/PackageInterface.php',
	'SuperKernel\\Contract\\PathResolverInterface'                         => __DIR__ . '/../contract/src/PathResolverInterface.php',
	'SuperKernel\\Contract\\ReflectionCollectorInterface'                  => __DIR__ . '/../contract/src/ReflectionCollectorInterface.php',
	'SuperKernel\\Contract\\StdoutLoggerInterface'                         => __DIR__ . '/../contract/src/StdoutLoggerInterface.php',
	'SuperKernel\\Di\\Attribute\\Definer'                                  => __DIR__ . '/../di/src/Attribute/Definer.php',
	'SuperKernel\\Di\\Attribute\\Resolver'                                 => __DIR__ . '/../di/src/Attribute/Resolver.php',
	'SuperKernel\\Di\\Container'                                           => __DIR__ . '/../di/src/Container.php',
	'SuperKernel\\Di\\Contract\\DefinerInterface'                          => __DIR__ . '/../di/src/Contract/DefinerInterface.php',
	'SuperKernel\\Di\\Contract\\DefinitionFactoryInterface'                => __DIR__ . '/../di/src/Contract/DefinitionFactoryInterface.php',
	'SuperKernel\\Di\\Contract\\DefinitionInterface'                       => __DIR__ . '/../di/src/Contract/DefinitionInterface.php',
	'SuperKernel\\Di\\Contract\\ResolverFactoryInterface'                  => __DIR__ . '/../di/src/Contract/ResolverFactoryInterface.php',
	'SuperKernel\\Di\\Contract\\ResolverInterface'                         => __DIR__ . '/../di/src/Contract/ResolverInterface.php',
	'SuperKernel\\Di\\Definer\\ObjectDefiner'                              => __DIR__ . '/../di/src/Definer/ObjectDefiner.php',
	'SuperKernel\\Di\\Definer\\ProviderDefiner'                            => __DIR__ . '/../di/src/Definer/ProviderDefiner.php',
	'SuperKernel\\Di\\Definition\\FactoryDefinition'                       => __DIR__ . '/../di/src/Definition/FactoryDefinition.php',
	'SuperKernel\\Di\\Definition\\MethodDefinition'                        => __DIR__ . '/../di/src/Definition/MethodDefinition.php',
	'SuperKernel\\Di\\Definition\\ObjectDefinition'                        => __DIR__ . '/../di/src/Definition/ObjectDefinition.php',
	'SuperKernel\\Di\\Definition\\PropertyDefinition'                      => __DIR__ . '/../di/src/Definition/PropertyDefinition.php',
	'SuperKernel\\Di\\Definition\\ProviderDefinition'                      => __DIR__ . '/../di/src/Definition/ProviderDefinition.php',
	'SuperKernel\\Di\\Exception\\ContainerException'                       => __DIR__ . '/../di/src/Exception/ContainerException.php',
	'SuperKernel\\Di\\Exception\\Container\\ProviderResolutionException'   => __DIR__ . '/../di/src/Exception/Container/ProviderResolutionException.php',
	'SuperKernel\\Di\\Exception\\Container\\ResolverException'             => __DIR__ . '/../di/src/Exception/Container/ResolverException.php',
	'SuperKernel\\Di\\Exception\\NotFoundException'                        => __DIR__ . '/../di/src/Exception/NotFoundException.php',
	'SuperKernel\\Di\\Factory\\DefinitionFactory'                          => __DIR__ . '/../di/src/Factory/DefinitionFactory.php',
	'SuperKernel\\Di\\Factory\\ResolverFactory'                            => __DIR__ . '/../di/src/Factory/ResolverFactory.php',
	'SuperKernel\\Di\\Resolver\\FactoryResolver'                           => __DIR__ . '/../di/src/Resolver/FactoryResolver.php',
	'SuperKernel\\Di\\Resolver\\MethodResolver'                            => __DIR__ . '/../di/src/Resolver/MethodResolver.php',
	'SuperKernel\\Di\\Resolver\\ObjectResolver'                            => __DIR__ . '/../di/src/Resolver/ObjectResolver.php',
	'SuperKernel\\Di\\Resolver\\PropertyResolver'                          => __DIR__ . '/../di/src/Resolver/PropertyResolver.php',
	'SuperKernel\\PathResolver\\Adapter\\ComposerAdapter'                  => __DIR__ . '/../path-resolver/src/Adapter/ComposerAdapter.php',
	'SuperKernel\\PathResolver\\Adapter\\NullAdapter'                      => __DIR__ . '/../path-resolver/src/Adapter/NullAdapter.php',
	'SuperKernel\\PathResolver\\Adapter\\StandardAdapter'                  => __DIR__ . '/../path-resolver/src/Adapter/StandardAdapter.php',
	'SuperKernel\\PathResolver\\Contract\\PathResolveAdapterInterface'     => __DIR__ . '/../path-resolver/src/Contract/PathResolveAdapterInterface.php',
	'SuperKernel\\PathResolver\\PathResolver'                              => __DIR__ . '/../path-resolver/src/PathResolver.php',
	'SuperKernel\\PathResolver\\Provider\\PathResolveAdapterProvider'      => __DIR__ . '/../path-resolver/src/Provider/PathResolveAdapterProvider.php',
	'SuperKernel\\ProcessHandler\\Contract\\ProcessHandlerInterface'       => __DIR__ . '/../process-handler/src/Contract/ProcessHandlerInterface.php',
	'SuperKernel\\ProcessHandler\\NullProcessHandler'                      => __DIR__ . '/../process-handler/src/NullProcessHandler.php',
	'SuperKernel\\ProcessHandler\\PcntlProcessHandler'                     => __DIR__ . '/../process-handler/src/PcntlProcessHandler.php',
	'SuperKernel\\ProcessHandler\\Provider\\ProcessHandlerProvider'        => __DIR__ . '/../process-handler/src/Provider/ProcessHandlerProvider.php',
	'SuperKernel\\Reflector\\Provider\\ReflectionCollectorProvider'        => __DIR__ . '/../reflector/src/Provider/ReflectionCollectorProvider.php',
	'SuperKernel\\Reflector\\ReflectionCollector'                          => __DIR__ . '/../reflector/src/ReflectionCollector.php',
	'SuperKernel\\Tokenizer\\Contract\\TokenReaderInterface'               => __DIR__ . '/../tokenizer/src/Contract/TokenReaderInterface.php',
	'SuperKernel\\Tokenizer\\Reader\\FullTokenReader'                      => __DIR__ . '/../tokenizer/src/Reader/FullTokenReader.php',
	'SuperKernel\\Tokenizer\\TokenParser'                                  => __DIR__ . '/../tokenizer/src/TokenParser.php',
];

spl_autoload_register(static function ($class) use ($classMap) {
	if (isset($classMap[$class])) {
		require $classMap[$class];
	}
});